### ISSUE TITLE
About the command examples in the README.

### ISSUE THREAD

**Issue by v8yte** [Jumpaku/cyamli#30]
Shouldn't we fix the command examples in the README?
```
go run main.go cli.gen.go list -c=config.yaml
go run main.go cli.gen.go fetch -c=config.yaml -v table1 table2
```

**Comment by Jumpaku** [comment]
Thanks for pointing that out!

I think that the README should be fixed as you say. Could you send a PR?

**Comment by v8yte** [comment]
OK. I'll make a pull request after I finish eating.
